version: '3.8'

services:
  medical-rag-api:
    build: .
    image: medical-rag-app:latest
    ports:
      - "8000:8000"
    volumes:
      - ./huggingface_data:/root/.cache/huggingface
    restart: always